name: AutoGrade
description: Mobile Based Auto Grading
full_description: 'Grade &amp; score multiple-choice tests, quizzes, and assessment papers by using your mobile device&#39;s camera as a scanner.<br>
<br>Quick Start:
<br>1. Press <b>Sheets</b> and choose multiple answer sheet
<br>2. Press <b>Create my first quiz</b>. Fill in a quiz information
<br>3. Select your quiz
<br>4. Press <b>Key</b>. Press <b>Create my first key</b>. Enter your key or open camera to scan the key
<br>5. Press <b>Grade</b> to start scanning papers. Follow the guide shown in the app
<br>6. Press <b>Review</b> to see your result'
android: 'https://play.google.com/store/apps/details?id=app.autograde.android'
iOS: https://apps.apple.com/us/app/autograde/id1576712386
screenshots:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  - 5.jpg
# producthunt: https://telegra.ph/Replace-this-link-07-23
# companies:
  # - url: https://telegra.ph/Replace-this-link-07-23
    # image: androidpolice.png
  # - url: https://telegra.ph/Replace-this-link-07-23
    # image: producthunt.png
